theme: jekyll-theme-architect
title: RFI-File-Monitor
description: The Official Manual

baseurl: /rfi-file-monitor
permalink: /:categories/:year/:month/:day/:title/


collections:
  operations:
    output: true
  engines:
    output: true
